MIN_DATE_DELTA = -1000
MAX_DATE_DELTA = 1000

MAX_STRING_LENGTH = 20

DATASOURCE_FILE_MANDATORY_COLUMNS = ['reference_date', 'delivery_begin', 'delivery_end', 'created_at']
DATASOURCE_FILE_TIME_FORMAT = "%Y-%m-%d %H:%M:%S"

DATASOURCE_FILE_REFERENCE_DATE_FROM = [1, 1, 2021]
DATASOURCE_FILE_REFERENCE_DATE_TO = [31, 12, 2021]

DATAOSURCE_FILE_DELIVERY_FROM = [1, 1, 2022]
DATASOURCE_FILE_DELIVERY_TO = [31, 1, 2022]

DATASOURCE_TYPES = [str, int]

RANDOM_STRING_MAX_LEN = 20
